### PR TITLE
1.74 changes. bIsDistracted and MaxScore

### PR DESCRIPTION
**Pull request by Gutbuster**
Added the new fields bIsDistracted and MaxScore that were added in 1.74.

### CODE REVIEW

**Comment by jjbott** [comment]
Thanks! I hadnt seen MaxScore  yet

**Comment by tfausak** [comment]
Do you have an example of a replay with the `TAGame.GameEvent_Soccar_TA:MaxScore` field?

**Comment by Gutbuster** [comment]
@tfausak I do. I created a quick sample by creating private match with bots and setting the MaxScore mutator to 1. You can grab it from [here](https://drive.google.com/open?id=1bz2PveEl9mrhPSyTe7lyI0QeK4VDmh06)

**Comment by tfausak** [comment]
Thanks!

**Pull request merged**
